export const RECIPES_DELETE = 'RECIPES_DELETE'
export const RECIPES_DELETE_SUCCESS = 'RECIPES_DELETE_SUCCESS'
export const RECIPES_DELETE_FAILURE = 'RECIPES_DELETE_FAILURE'

export const RECIPES_CREATE = 'RECIPES_CREATE'
export const RECIPES_CREATE_SUCCESS = 'RECIPES_CREATE_SUCCESS'
export const RECIPES_CREATE_FAILURE = 'RECIPES_CREATE_FAILURE'

export const RECIPES_EDIT = 'RECIPES_EDIT'
export const RECIPES_EDIT_SUCCESS = 'RECIPES_EDIT_SUCCESS'
export const RECIPES_EDIT_FAILURE = 'RECIPES_EDIT_FAILURE'

export const RECIPES_GET = 'RECIPES_GET'
export const RECIPES_GET_SUCCESS = 'RECIPES_GET_SUCCESS'
export const RECIPES_GET_FAILURE = 'RECIPES_GET_FAILURE'


export const RECIPES_TOGGLE_VIEW = 'RECIPES_TOGGLE_VIEW'
export const RECIPES_TOGGLE_EDIT = 'RECIPES_TOGGLE_EDIT'
export const RECIPES_HANDLE_EDIT = 'RECIPES_HANDLE_EDIT'
export const RECIPES_TOGGLE_CREATE = 'RECIPES_TOGGLE_CREATE'
export const RECIPES_HANDLE_CREATE = 'RECIPES_HANDLE_CREATE'

export const SEARCH_TOGGLE = 'SEARCH_TOGGLE'
export const SEARCH_UPDATE_TERMS = 'SEARCH_UPDATE_TERMS'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

//show recipe action types
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_NAME = 'SHOW_NAME'
export const SHOW_INGREDIENTS = 'SHOW_INGREDIENTS'
export const SHOW_INSTRUCTIONS = 'SHOW_INSTRUCTIONS'
export const SHOW_AUTHOR = 'SHOW_AUTHOR'

//search filter action types
export const BY_ALL = 'BY_ALL'
export const BY_NAME = 'BY_NAME'
export const BY_INGREDIENTS = 'BY_INGREDIENTS'
export const BY_INSTRUCTIONS = 'BY_INSTRUCTIONS'
export const BY_AUTHOR = 'BY_AUTHOR'

//session action types
export const SESSION_LOGIN_REQUEST = 'SESSION_LOGIN_REQUEST'
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS'
export const SESSION_LOGIN_FAILURE = 'SESSION_LOGIN_FAILURE'

export const SESSION_LOGOUT_REQUEST = 'SESSION_LOGOUT_REQUEST'
export const SESSION_LOGOUT_SUCCESS = 'SESSION_LOGOUT_SUCCESS'
export const SESSION_LOGOUT_FAILURE = 'SESSION_LOGOUT_FAILURE'

export const SESSION_CHECK_STATUS_REQUEST = 'SESSION_CHECK_STATUS_REQUEST'
export const SESSION_CHECK_STATUS_SUCCESS = 'SESSION_CHECK_STATUS_SUCCESS'
export const SESSION_CHECK_STATUS_FAILURE = 'SESSION_CHECK_STATUS_FAILURE'

//header state
export const HEADER_BUTTON_SELECT = 'HEADER_BUTTON_SELECT'
export const HEADER_HANDLE_INPUT = 'HEADER_HANDLE_INPUT'
export const HEADER_MEASURE_HEIGHT = 'HEADER_MEASURE_HEIGHT'
