export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST'
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS'
export const RECIPE_DELETE_FAILURE = 'RECIPE_DELETE_FAILURE'

export const RECIPE_CREATE_REQUEST = 'RECIPE_CREATE_REQUEST'
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS'
export const RECIPE_CREATE_FAILURE = 'RECIPE_CREATE_FAILURE'

export const RECIPE_UPDATE_REQUEST = 'RECIPE_UPDATE_REQUEST'
export const RECIPE_UPDATE_SUCCESS = 'RECIPE_UPDATE_SUCCESS'
export const RECIPE_UPDATE_FAILURE = 'RECIPE_UPDATE_FAILURE'

export const RECIPE_FORM_CHANGE = 'RECIPE_FORM_CHANGE'
export const RECIPE_FORM_TOGGLE = 'RECIPE_FORM_TOGGLE'

export const RECIPES_REQUEST = 'RECIPES_REQUEST'
export const RECIPES_SUCCESS = 'RECIPES_SUCCESS'
export const RECIPES_FAILURE = 'RECIPES_FAILURE'

export const CREATE_RECIPE = 'CREATE_RECIPE'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const TOGGLE_RECIPE = 'TOGGLE_RECIPE'

export const IS_EDITING = 'IS_EDITING'

export const SEARCH_CONTRIBUTOR = 'SEARCH_CONTRIBUTOR'
export const SEARCH_INGREDIENTS = 'SEARCH_INGREDIENTS'
export const SEARCH_INSTRUCTIONS = 'SEARCH_INSTRUCTIONS'
export const SEARCH_NAME = 'SEARCH_NAME'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS'
export const SET_SEARCH_TERMS = 'SET_SEARCH_TERMS'

//show recipe action types
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_NAME = 'SHOW_NAME'
export const SHOW_INGREDIENTS = 'SHOW_INGREDIENTS'
export const SHOW_INSTRUCTIONS = 'SHOW_INSTRUCTIONS'
export const SHOW_AUTHOR = 'SHOW_AUTHOR'

//search filter action types
export const BY_ALL = 'BY_ALL'
export const BY_NAME = 'BY_NAME'
export const BY_INGREDIENTS = 'BY_INGREDIENTS'
export const BY_INSTRUCTIONS = 'BY_INSTRUCTIONS'
export const BY_AUTHOR = 'BY_AUTHOR'

//session action types
export const SESSION_LOGIN_REQUEST = 'SESSION_LOGIN_REQUEST'
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS'
export const SESSION_LOGIN_FAILURE = 'SESSION_LOGIN_FAILURE'

export const SESSION_LOGOUT_REQUEST = 'SESSION_LOGOUT_REQUEST'
export const SESSION_LOGOUT_SUCCESS = 'SESSION_LOGOUT_SUCCESS'
export const SESSION_LOGOUT_FAILURE = 'SESSION_LOGOUT_FAILURE'

export const SESSION_CHECK_STATUS_REQUEST = 'SESSION_CHECK_STATUS_REQUEST'
export const SESSION_CHECK_STATUS_SUCCESS = 'SESSION_CHECK_STATUS_SUCCESS'
export const SESSION_CHECK_STATUS_FAILURE = 'SESSION_CHECK_STATUS_FAILURE'

//header state
export const HEADER_BUTTON_SELECT = 'HEADER_BUTTON_SELECT'
export const HEADER_HANDLE_INPUT = 'HEADER_HANDLE_INPUT'
