export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS';
export const RECIPE_DELETE_FAILURE = 'RECIPE_DELETE_FAILURE';

export const RECIPE_CREATE_REQUEST = 'RECIPE_CREATE_REQUEST';
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS';
export const RECIPE_CREATE_FAILURE = 'RECIPE_CREATE_FAILURE';

export const RECIPE_UPDATE_REQUEST = 'RECIPE_UPDATE_REQUEST';
export const RECIPE_UPDATE_SUCCESS = 'RECIPE_UPDATE_SUCCESS';
export const RECIPE_UPDATE_FAILURE = 'RECIPE_UPDATE_FAILURE';

export const RECIPES_REQUEST = 'RECIPES_REQUEST';
export const RECIPES_SUCCESS = 'RECIPES_SUCCESS';
export const RECIPES_FAILURE = 'RECIPES_FAILURE';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const TOGGLE_RECIPE = 'TOGGLE_RECIPE';

export const IS_EDITING = 'IS_EDITING';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';
export const SET_SEARCH_TERMS = 'SET_SEARCH_TERMS';

//show recipe action types
export const SHOW_ALL =  'SHOW_ALL';
export const SHOW_NAME =  'SHOW_NAME';
export const SHOW_INGREDIENTS =  'SHOW_INGREDIENTS';
export const SHOW_INSTRUCTIONS =  'SHOW_INSTRUCTIONS';
export const SHOW_AUTHOR =  'SHOW_AUTHOR';

//search filter action types
export const BY_ALL =  'BY_ALL';
export const BY_NAME =  'BY_NAME';
export const BY_INGREDIENTS =  'BY_INGREDIENTS';
export const BY_INSTRUCTIONS =  'BY_INSTRUCTIONS';
export const BY_AUTHOR =  'BY_AUTHOR';
